# Dependabot version updates are disabled by ignoring all deps.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/image-uploading-with-node-and-cloudinary"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-with-express"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
